language: python

python: 3.4

branches:
    only:
        - master
        - develop

install: pip install -r requirements-tests.txt

script: py.test

after_script:
    pip install --quiet --use-mirrors coveralls coverage;
    coverage run -m py.test
    coverage report
    coveralls;
